


###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "fullName": "John Smith",
    "email": "john.smith@example.com",
    "password": "S3cur3P@ssw0rd!",
    "mobileNo": "+1-555-987-6543",
    "age": 34,
    "role": "User",
    "userName": "johnsmith"
}


###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "fullName": "John Smith",
    "email": "john.smith@example.com",
    "password": "S3cur3P@ssw0rd!",
    "mobileNo": "+1-555-987-6543",
    "age": 34,
    "role": "User",
    "userName": "johnsmith"
}

###
GET http://localhost:5000/api/searchAirport?airportStr=De
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmM4MWFiZDkyNWRjNzY0YWNhMjE3MzYiLCJpYXQiOjE3MjQzOTAwNzcsImV4cCI6MTc1NTkyNjA3N30.AL3pDIMkTM4KTTPN_nz7EAHNPYE6O7lRI1F0TzKjPzs

###
GET http://localhost:5000/api/searchFlight?origin=EWR&dest=BOS&travelDate=2019-08-15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmQyY2UyOWUwNGU1YjljNGI2MTk2NDciLCJpYXQiOjE3MjUwOTEzNzMsImV4cCI6MTc1NjYyNzM3M30.wa__k2el0ZDO-ZY-fQzXai63GCDMZ3N4I6PiO0FJ-rA


###
POST http://localhost:5000/api/test
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmMwODE1Yjg2ZGJkZWNmY2VkZDE4MDAiLCJpYXQiOjE3MjM4OTIxMjcsImV4cCI6MTc1NTQyODEyN30.tEkKLHcSAkXubxo9iilNBbGKyA7PBTE18iys3L8IzMc
Cookie: /auth/permanentToken=s%3Aj%3A%7B%22id%22%3A%2266b76018f168caf69e652641%22%7D.tplsriebwqrrKjp6vOllV4YP%2BB3I%2B%2FWvjTT1krNRQmo; Max-Age=8640000; Domain=http://localhost:5000; Path=/refreshToken; Expires=Tue, 19 Nov 2024 13:21:54 GMT; HttpOnly; Secure; SameSite=Strict
Content-Type: application/json

{

}
###
POST http://192.168.0.163:5000/auth/refreshToken
Cookie: permanentToken=s%3Aj%3A%7B%22id%22%3A%2266b76018f168caf69e652641%22%7D.tplsriebwqrrKjp6vOllV4YP%2BB3I%2B%2FWvjTT1krNRQmo; Max-Age=8640000; Domain=http://localhost:5000; Path=/auth/refreshToken; Expires=Tue, 19 Nov 2024 13:27:23 GMT; HttpOnly; Secure; SameSite=Strict,connect.sid=s%3A3ZCsgSMr9UWbqbHyZDOBdD4ddOaqD66i.zPOODHWt6b59mGcSsp6T7il82bMG0ifP4yHQ4%2FogdwM; Path=/; Expires=Mon, 12 Aug 2024 13:27:23 GMT; HttpOnly
Content-Type: application/json

{

}
