

###

POST http://localhost:5000/addUser
Content-Type: application/json

{
  "user_name": "alice_wonder",
  "full_name": "Alice Wonderland",
  "email": "alice.wonderland@example.com",
  "password": "mySecretPass456",
  "confirm_password": "mySecretPass456"
}
###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "user_name": "alice_wonder",
  "full_name": "Alice Wonderland",
  "email": "alice.wonderland@example.com",
  "password": "mySecretPass456",
  "confirm_password": "mySecretPass456"
}