spring.application.name=microservice

server.port=8080

# Kafka broker address
spring.kafka.bootstrap-servers=localhost:9092

# === PRODUCER CONFIG ===
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# === CONSUMER CONFIG ===
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Use ErrorHandlingDeserializer for key and value
# spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
# spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate actual deserialization to these classes
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.apache.kafka.common.serialization.StringDeserializer


# Trust all packages for deserialization (or specify your package)
spring.kafka.consumer.properties.spring.json.trusted.packages=*




# External service URLs
external.services.auth_service=http://localhost:3500
external.services.email_service=http://localhost:3000
external.services.websocket_service=http://localhost:8080
external.services.app_service=http://localhost:5000
