

### Register Test

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Test5",
    "password":"Test!321",
    "email": "sk.bilal.md@gmail.com",
    "dob": "2000-03-06"
}



### Login Test

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "sk.bilal.md@gmail.com",
    "password":"Test!321"
}

### Forget Password

POST http://localhost:3000/api/auth/forgetPassword

{
    "email": "sk.bilal.md@gmail.com"
}

### Verify User

GET http://localhost:5000/api/auth/verifyUser
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMiLCJpYXQiOjE3NDA5MTc1NDUsImV4cCI6MTc0MzUwOTU0NX0.s7nbL9UN494zncYBD0RNnfa-HsuF5_vZBHUhA2Ft0Gs; Path=/