

###
POST http://localhost:5000/file/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="image.png"
Content-Type: image/png

< ./image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

GET http://localhost:5000/file/image/b2a2b6cb-3c35-435c-ac3d-f7d0f936cafa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE3NDUwOTUwNDAsImV4cCI6MTc0NzY4NzA0MH0.JB1nTzgaGPk-fdWyYt3pnrzydcobP0XDMSaktuj0xeU

###

DELETE  http://localhost:5000/file/image/19d3cc59-68ef-459a-92d0-2e77aab2a7d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE3NDUwOTUwNDAsImV4cCI6MTc0NzY4NzA0MH0.JB1nTzgaGPk-fdWyYt3pnrzydcobP0XDMSaktuj0xeU