

### Users

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJpYXQiOjE3MzU0Njc0MTAsImV4cCI6MTczODA1OTQxMH0.fohC3WDUC9q8x90N14aD_oc6_rkdkTudzvWoxwX2Jw0