

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "firstName":"user1",
    "lastName":"user1lastname",
    "email":"user1@gmail.com",
    "password":"Test!321"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"user1@gmail.com",
    "password":"Test!321"
}

###
GET http://localhost:5000/api/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjU3M2FlYjc3YjI0YjBkN2RiMGM3Y2EiLCJpYXQiOjE3MTcwODM5MTMsImV4cCI6MTcxNzA4NzUxM30.XoUWQpbUl56huUaLZScFh9drUtFXicxDKy5pbzqCtDs

###
GET http://localhost:5000/api/user/66573aeb77b24b0d7db0c7ca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjU3M2FlYjc3YjI0YjBkN2RiMGM3Y2EiLCJpYXQiOjE3MTcwODM5MTMsImV4cCI6MTcxNzA4NzUxM30.XoUWQpbUl56huUaLZScFh9drUtFXicxDKy5pbzqCtDs




