apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 5000   # Service port
    targetPort: 5000   # Target port of the pods
    nodePort: 30000
