apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 6001   # Service port
    targetPort: 5000   # Target port of the pods
    nodePort: 31000
  type: LoadBalancer
