

### Register User
POST http://localhost:3500/auth/register
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "test123",
  "username": "testuser1",
  "confirmPassword": "test123"
}

### Login User
POST http://localhost:3500/auth/login
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "test123"
}

### Verify Token
GET http://localhost:3500/auth/verify?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBmMWE2ZTM1LTNjNGItNGJhNi04NDZiLTJmMzgyMWEyNTJmNSIsInVzZXJuYW1lIjoidGVzdHVzZXIxIiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20iLCJpYXQiOjE3NTY2NDI2MDUsImV4cCI6MTc1NjY0NjIwNX0.q4IPcA1bjy4rpZLOoO02S3zvab0iyVkKfwGKIwe71YA
Content-Type: application/json

# { 
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImlhdCI6MTc1NTU5NDI3NSwiZXhwIjoxNzU1NTk3ODc1fQ.k88q_pcWvHBHmgEc_SBAUFbsvQ4ymkIXksu3p8GfQlI"
# }

### User Verification
POST http://localhost:3500/auth/verify-status
Content-Type: application/json

{
  "userId": 1
}