

### Register User
POST http://localhost:3500/auth/register
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "test123",
  "username": "testuser1",
  "confirmPassword": "test123"
}

### Login User
POST http://localhost:3500/auth/login
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "test123"
}

### Verify Token
GET http://localhost:3500/auth/verify?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImlhdCI6MTc1NTcwNDk4MywiZXhwIjoxNzU1NzA4NTgzfQ.255Vut5aF7HEf6KlUnvJMqK8tzJ2nFBetOBdf1rervo
Content-Type: application/json

# { 
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImlhdCI6MTc1NTU5NDI3NSwiZXhwIjoxNzU1NTk3ODc1fQ.k88q_pcWvHBHmgEc_SBAUFbsvQ4ymkIXksu3p8GfQlI"
# }

### User Verification
POST http://localhost:3500/auth/verify-status
Content-Type: application/json

{
  "userId": 1
}