apiVersion: v1
kind: Secret
metadata:
  name: node-app-secret
type: Opaque
data:
  PORT: NTAwMA==
  MONGO_URL: bW9uZ29kYjovL21vbmdvLWxiLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvP3JlcGxpY2FTZXQ9cnMwJnJlYWRQcmVmZXJlbmNlPXNlY29uZGFyeVByZWZlcnJlZA==
