apiVersion: v1
kind: Service
metadata:
  name: mycluster-router
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: router
    app.kubernetes.io/instance: mycluster
  ports:
    - name: mysql
      port: 3306
      targetPort: 6446  # 👈 This is important!
      nodePort: 30306   # 👈 Customize if needed (range: 30000–32767)
