spring.application.name=auth_ms

spring.datasource.url=jdbc:mysql://localhost:3306/auth
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

# Kafka bootstrap servers
spring.kafka.bootstrap-servers=localhost:9092

# Key deserializer (String)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Value deserializer (JSON)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Specify trusted packages for deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.websocket.microservice
spring.kafka.consumer.properties.spring.json.value.default.type=com.websocket.microservice.service.events.UserEvent

# Define default Java type to deserialize the JSON into
# spring.kafka.consumer.properties.spring.json.value.default.type=com.example.model.YourClass

# Optional: Don't rely on type headers in Kafka records
spring.kafka.consumer.properties.spring.json.use.type.headers=false