

###
POST http://localhost:8080/authenticate/login
Content-Type: application/json

{
    "username":"bilal",
    "password":"bilalpw"
}

###
POST http://localhost:8080/authenticate/register
Content-Type: application/json

{
    "userName":"bilal",
    "password":"bilalpw",
    "age":21,
    "email":"bilal12@gmail.com"
}

###
GET http://localhost:8080/api/employees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcxNjU3NjE2NCwiZXhwIjoxNzM0NTc2MTY0fQ.fjXubIh1jBi-JYQxvSwk0yEGuNBsu_jJnjr9xnEQ8bS8dfe-ET2h0TbBDRSu9aTZUHGEzeiC5RNgW-LRzd-1dg

