

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "firstName":"user1",
    "lastName":"user1lastname",
    "email":"user1@gmail.com",
    "password":"Test!321"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"user1@gmail.com",
    "password":"Test!321"
}

###
GET http://localhost:5000/api/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjU0OTMwYjMwYThiYzNlMzM5MDUwYzAiLCJpYXQiOjE3MTY4MTg3NjgsImV4cCI6MTcxNjgyMjM2OH0.684OTJKYrsQxhBdfEQSPAJj3A4-TuQ5AZDk8YSXc7Lw




