external.services.auth_service=http://localhost:3500
external.services.email_service=http://localhost:3000
external.services.websocket_service=http://localhost:8080
external.services.app_service=http://localhost:5000

database.url=jdbc:mysql://localhost:3306/mydb
database.username=root
database.password=root
database.driver=com.mysql.cj.jdbc.Driver
database.ddl-auto=update
